function[result] = f(U, K, a, t)
z=U*C(a,t);
result = ...
    ((U/(pi*a)).^(1.5))*...
    (2*(1i^(K+1))/(a.^2))*...
    ((pi/((1/a)+(1i*t/2))).^(3/2))*...
    (((B(a,t)*(besselj(K+2,z)+besselj(K,z)))+...
    (1i*D(B(a,t),a,U,t)*besselj(K+1,z)))+...
    ((1i*B(a,t)*(besselj(K+1,z)-besselj(K-1,z)))+...
    (D(B(a,t),a,U,t)*besselj(K,z)))*exp(1i*t));